### ISSUE TITLE
For Python 3.7

### ISSUE THREAD

**Issue by Solverin** [zadarma/user-api-v1-py#2]
For Python 3.7 replaced 
import requests
by 
import urllib.request 
in api.py

**Comment by Nine-Black** [comment]
> For Python 3.7 replaced
> import requests
> by
> import urllib.request
> in api.py

+++ the urllib.request (https://github.com/urllib3/urllib3) - is part of the Python standard library stdlib.  
Most (if not all) of the python stdlib is fugly because it just wasn't well designed, not because it was a product of a more innocent time (just look on documentation https://docs.python.org/3/library/urllib.request.html#module-urllib.request)
And requests-library in contrast is more elegant, simple and friendly for newbies. 

P.S. The official Python docs recommend Requests as the standard library for performing high level HTTP requests. It's in a very visible banner on the urllib page. (https://docs.python.org/3/library/urllib.request.html#module-urllib.request)

**Comment by gostkov** [comment]
requests library supported from python2 and python3 without some changes in code, if you prefer urllib.request, you can create fork or pull request.
